Updated start and stop server scripts

diff --git a/scripts/start_server b/scripts/start_server
--- a/scripts/start_server
+++ b/scripts/start_server
@@ -1,2 +1,12 @@
 #!/bin/bash
-systemctl start httpd
+# Check if httpd is installed
+httpd -v > /dev/null 2>&1
+if [ $? -eq 0 ]
+then
+    echo "httpd is installed, starting service."
+    sudo service httpd start
+else
+    echo "httpd not found. Installing httpd."
+    sudo yum install httpd -y
+    sudo service httpd start
+fi
diff --git a/scripts/stop_server b/scripts/stop_server
--- a/scripts/stop_server
+++ b/scripts/stop_server
@@ -1,2 +1,10 @@
 #!/bin/bash
-systemctl stop httpd
+# Check if httpd is installed
+httpd -v > /dev/null 2>&1
+if [ $? -eq 0 ]
+then
+    echo "httpd is installed, stopping service."
+    sudo service httpd stop
+else
+    echo "httpd not found. No need to stop service."
+fi
